add_newline = false

# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’ 
format = """
[â•­â”€](8)$directory$git_branch$git_status
[â•°â”€](8)$character
"""
[fill]
symbol = " "
disabled = false

[character]
success_symbol = "[ï„…](green)"
error_symbol = "[ï„…](red)"

[os]
format = "[î‚¶](fg:white)[$symbol]($style)[î‚¼](fg:white bg:blue)"
style = "bg:white fg:black"
disabled = false

[os.symbols]
Windows = "î˜ª "
Arch = "ïŒƒ "
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = "îœ¥ "
format = "[ ï…¸ ](green)[$branch](green)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "x"
ahead = " ğŸğŸ’¨ "
behind = " ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤· â€"
stashed = " ğŸ“¦ "
modified = "+"
staged = '[++\($count\)](green)'
renamed = " âœï¸ "
deleted = "-"

[hostname]
ssh_only = false
format =  "[@$hostname](bg:color4 fg:color3)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bg:color4 fg:color3"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

#[directory]
#home_symbol = " ï‘­ "
#read_only = " ï‘– "
#style = "bg:green fg:black"
#truncation_length = 6
#truncation_symbol = "â€¢â€¢/"
#format = '[î‚¶](bold fg:green)[$path ]($style)[î‚´](bold fg:green)'
[directory]
format = "[ ï» ](fg:blue)[$path](fg:blue)"
style = "bg:none fg:green"
truncation_length = 6
truncate_to_repo = false
truncation_symbol = "â€¢â€¢/"


#[directory.substitutions]
#"Desktop" = " ï’© "
#"Documents" = " ï’¥ "
#"Downloads" = " ï‰ "
#"Music" = " ó°ˆ "
#"Pictures" = " ï "
#"Videos" = " ï”¬ "

[cmd_duration]
min_time = 0
format = '[ $duration](bold bg:8 fg:white)[î‚´](fg:8)'

[palettes.kanagawa_dragon]
color1 = "#181616"
color2 = "#c5c9c5"
color3 = "#8a9a7b"
color4 = "#403a3a"

#0 = Black
#1 = Red
#2 = Green
#3 = Yellow
#4 = Blue
#5 = Magenta
#6 = Cyan
#7 = Light Gray
#8 = Dark Gray (a veces considerado como un gris plomo)
#9 = Light Red
#10 = Light Green
#11 = Light Yellow
#12 = Light Blue
#13 = Light Magenta
#14 = Light Cyan
#15 = White
